dist: bionic
sudo: false
language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test # Allows new version of g++ to be used
    packages:
      - g++-9

install:
  - pip3 install --user conan cmake


script:
  - mkdir -p build
  - cd build
  - CXX=/usr/bin/g++-9 cmake ..
  - cmake --build . -- -j2
