dist: bionic
sudo: false
language: python

python:
  - 3.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test # Allows new version of g++ to be used
    packages:
      - g++-9
      - gcc-9

install:
  - pip3 install conan cmake


script:
  - mkdir -p build
  - cd build
  - CXX=/usr/bin/g++-9 cmake ..
  - cmake --build . -- -j2
